[package]
name = "otpkey"
version = "0.1.0"
authors = ["snow <snow@datagirl.xyz>"]
edition = "2018"

[dependencies]
ring = "0.14"
failure = "0.1.5"
base32 = "0.4"
base64 = "0.10"
qrcode = "0.10"
image = "0.21"
